name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AppClipsStudio
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: 
  - muhittincamdali
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for AppClipsStudio!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import AppClipsStudio
        2. Create an AppClip configuration
        3. Call method X
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: Please provide a minimal code example that reproduces the issue
      render: swift
      placeholder: |
        import AppClipsStudio
        
        let core = AppClipCore.shared
        // Your code here
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: AppClipsStudio Version
      description: What version of AppClipsStudio are you running?
      options:
        - "1.0.0 (latest)"
        - "0.9.x"
        - "0.8.x"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - macOS
        - watchOS
        - tvOS
        - visionOS
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS/Platform Version
      description: What version of iOS/platform are you running?
      placeholder: "e.g., iOS 18.0, macOS 14.0"
    validations:
      required: true

  - type: input
    id: xcode-version
    attributes:
      label: Xcode Version
      description: What version of Xcode are you using?
      placeholder: "e.g., Xcode 15.0"
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which AppClipsStudio module is affected?
      options:
        - "AppClipCore"
        - "AppClipRouter"
        - "AppClipAnalytics"
        - "AppClipNetworking"
        - "AppClipUI"
        - "AppClipStorage"
        - "AppClipSecurity"
        - "AppClipTesting"
        - "Multiple modules"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true